#!/bin/bash

set user=$(whoami)

case "$user" in
  root)
    for "ca.desrt.dconf-editor.Settings show-warning false",
        "ca.desrt.dconf-editor.Settings sort-case-sensitive false",
        "ca.desrt.dconf-editor.Settings window-is-maximized true",
        "com.canonical.indicator.datetime alarm-haptic-feedback 'none'",
        "com.canonical.indicator.datetime show-calendar true",
        "com.canonical.indicator.datetime show-clock true",
        "com.canonical.indicator.datetime show-date true",
        "com.canonical.indicator.datetime show-day true",
        "com.canonical.indicator.datetime show-year true",
        "com.canonical.indicator.datetime timezone-name 'Central'",
        "com.canonical.indicator.power icon-policy 'never'",
        "com.canonical.unity-greeter background '/usr/share/backgrounds/warty-final-ubuntu.png'",
        "com.canonical.unity-greeter background-color '#2C001E'",
        "com.canonical.unity-greeter background-logo '/usr/share/unity-greeter/cof.png'",
        "com.canonical.unity-greeter draw-grid false",
        "com.canonical.unity-greeter draw-user-backgrounds false",
        "com.canonical.unity-greeter font-name 'Ubuntu 11'",
        "com.canonical.unity-greeter icon-theme-name 'Flat-Remix-Dark'",
        "com.canonical.unity-greeter logo '/usr/share/unity-greeter/logo.png'",
        "com.canonical.unity-greeter play-ready-sound false",
        "com.canonical.unity-greeter theme-name 'Obsidian-2'",
        "com.canonical.unity-greeter xft-hintstyle 'hintslight'",
        "com.ubuntu.touch.network gps false",
        "com.ubuntu.touch.sound silent-mode true",
        "com.ubuntu.touch.system rotation-lock true",
        "com.ubuntu.update-notifier no-show-notifications false",
        "com.ubuntu.update-notifier show-apport-crashes true",
        "com.ubuntu.user-interface.desktop cursor-size 32",
        "org.gnome.eog.ui disable-trash-confirmation",
        "org.gnome.eog.ui image-gallery true",
        "org.gnome.eog.ui image-gallery-position 'left'",
        "org.gnome.eog.ui image-gallery-resizable true",
        "org.gnome.eog.ui propsdialog-netbook-mode false",
        "org.gnome.eog.ui scroll-buttons false",
        "org.gnome.eog.ui statusbar false",
        "org.gnome.gedit.plugins active-plugins ['docinfo', 'externaltools', 'filebrowser', 'modelines', 'pythonconsole', 'quickopen', 'sort', 'snippets', 'spell', 'time']",
        "org.gnome.gedit.plugins.filebrowser enable-remote true",
        "org.gnome.gedit.plugins.filebrowser.nautilus confirm-trash false",
        "org.gnome.gedit.plugins.pythonconsole font 'Hack 10'",
        "org.gnome.gedit.plugins.time custom-format '%a %e %B %Y, %H%M %Z'",
        "org.gnome.gedit.plugins.time prompt-type 'use-custom-format'",
        "org.gnome.gedit.preferences.editor auto-indent true",
        "org.gnome.gedit.preferences.editor bracket-matching true",
        "org.gnome.gedit.preferences.editor display-line-numbers true",
        "org.gnome.gedit.preferences.editor display-overview-map true",
        "org.gnome.gedit.preferences.editor editor-font 'Hack 10'",
        "org.gnome.gedit.preferences.editor ensure-trailing-newline true",
        "org.gnome.gedit.preferences.editor insert-spaces true",
        "org.gnome.gedit.preferences.editor scheme 'cobalt'",
        "org.gnome.gedit.preferences.editor search-highlighting true",
        "org.gnome.gedit.preferences.editor syntax-highlighting true",
        "org.gnome.gedit.preferences.editor tabs-size 2",
        "org.gnome.login-screen allowed-failures 5",
        "org.gnome.login-screen disable-user-list false",
        "org.gnome.login-screen enable-password-authentication true",
        "org.gnome.login-screen enable-smartcard-authentication false",
        "org.gnome.nautilus.compression default-compression-format 'tar.xz'",
        "org.gnome.nautilus.desktop home-icon-visible false",
        "org.gnome.nautilus.desktop network-icon-visible false",
        "org.gnome.nautilus.desktop trash-icon-visible false",
        "org.gnome.nautilus.desktop volumes-visible true",
        "org.gnome.nautilus.list-view default-visible-columns ['name', 'size', 'owner', 'date_modified_with_time']",
        "org.gnome.nautilus.preferences always-use-location-entry true",
        "org.gnome.nautilus.preferences default-folder-viewer 'list-view'",
        "org.gnome.nautilus.preferences mouse-back-button 0",
        "org.gnome.nautilus.preferences mouse-forward-button 0",
        "org.gnome.nautilus.preferences mouse-use-extra-buttons false",
        "org.gnome.nautilus.preferences show-create-link true",
        "org.gnome.settings-daemon.plugins.power power-button-action 'suspend'",
        "org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 4800",
        "org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'suspend'",
        "org.gnome.settings-daemon.plugins.power sleep-inactive-battery-timeout 4800",
        "org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'suspend'",
        "org.gnome.software external-appstream-system-wide true",
        "org.gnome.gnome-system-monitor show-whose-processes 'all'",
        "org.gnome.nautilus.preferences confirm-trash false",
        "org.gnome.nautilus.preferences show-delete-permanently true",
        "org.gnome.nautilus.preferences show-hidden-files true",
        "org.gnome.online-accounts whitelisted-providers ['']"; do
      gsettings set $i
    done ;;
  *)
    set home_dir=$(getent passwd $user | cut -d':' -f6)
    for i in "ca.desrt.dconf-editor.Settings show-warning false",
             "ca.desrt.dconf-editor.Settings sort-case-sensitive false",
             "ca.desrt.dconf-editor.Settings window-is-maximized true",
             "com.canonical.indicator.datetime alarm-haptic-feedback 'none'",
             "com.canonical.indicator.datetime show-calendar true",
             "com.canonical.indicator.datetime show-clock true",
             "com.canonical.indicator.datetime show-date true",
             "com.canonical.indicator.datetime show-day true",
             "com.canonical.indicator.datetime show-year true",
             "com.canonical.indicator.datetime timezone-name 'Central'",
             "com.canonical.indicator.power icon-policy 'never'",
             "com.canonical.unity-greeter background '/usr/share/backgrounds/warty-final-ubuntu.png'",
             "com.canonical.unity-greeter background-color '#2C001E'",
             "com.canonical.unity-greeter background-logo '/usr/share/unity-greeter/cof.png'",
             "com.canonical.unity-greeter draw-grid false",
             "com.canonical.unity-greeter draw-user-backgrounds false",
             "com.canonical.unity-greeter font-name 'Ubuntu 11'",
             "com.canonical.unity-greeter icon-theme-name 'Flat-Remix-Dark'",
             "com.canonical.unity-greeter logo '/usr/share/unity-greeter/logo.png'",
             "com.canonical.unity-greeter play-ready-sound false",
             "com.canonical.unity-greeter theme-name 'Obsidian-2'",
             "com.canonical.unity-greeter xft-hintstyle 'hintslight'",
             "com.ubuntu.touch.network gps false",
             "com.ubuntu.touch.sound silent-mode true",
             "com.ubuntu.touch.system rotation-lock true",
             "com.ubuntu.update-notifier no-show-notifications false",
             "com.ubuntu.update-notifier show-apport-crashes true",
             "com.ubuntu.user-interface.desktop cursor-size 32",
             "org.gnome.calculator base 10",
             "org.gnome.calculator button-mode 'keyboard'",
             "org.gnome.calculator show-thousands true",
             "org.gnome.calculator show-zeroes false",
             "org.gnome.calendar active-view 'month'",
             "org.gnome.desktop.a11y always-show-text-caret false",
             "org.gnome.desktop.a11y always-show-universal-access-status false",
             "org.gnome.desktop.a11y.keyboard togglekeys-enable true",
             "org.gnome.desktop.app-folders folder-children []",
             "org.gnome.desktop.background draw-background true",
             "org.gnome.desktop.background picture-options 'spanned'",
             "org.gnome.desktop.calendar show-weekdate true",
             "org.gnome.desktop.datetime automatic-timezone true",
             "org.gnome.desktop.file-sharing bluetooth-accept-files 'ask'",
             "org.gnome.desktop.file-sharing require-password 'always'",
             "org.gnome.desktop.interface buttons-have-icons true",
             "org.gnome.desktop.interface clock-format '24h'",
             "org.gnome.desktop.interface clock-show-date true",
             "org.gnome.desktop.interface clock-show-seconds false",
             "org.gnome.desktop.interface cursor-blink true",
             "org.gnome.desktop.interface cursor-theme 'DMZhaloR32'",
             "org.gnome.desktop.interface gtk-enable-primary-paste false",
             "org.gnome.desktop.interface gtk-theme 'Obsidian-2'",
             "org.gnome.desktop.interface icon-theme 'Flat-Remix-Dark'",
             "org.gnome.desktop.interface monospace-font-name 'Hack 10'",
             "org.gnome.desktop.interface show-battery-percentage false",
             "org.gnome.desktop.interface show-input-method-menu false",
             "org.gnome.desktop.interface show-unicode-menu false",
             "org.gnome.desktop.media-handling automount true",
             "org.gnome.desktop.media-handling automount-open false",
             "org.gnome.desktop.media-handling autorun-never true",
             "org.gnome.desktop.notifications show-in-lock-screen false",
             "org.gnome.desktop.peripherals.mouse accel-profile 'adaptive'",
             "org.gnome.desktop.peripherals.touchpad click-method 'none'",
             "org.gnome.desktop.peripherals.touchpad disable-while-typing true",
             "org.gnome.desktop.peripherals.touchpad left-handed 'right'",
             "org.gnome.desktop.peripherals.touchpad scroll-method 'disabled'",
             "org.gnome.desktop.peripherals.touchpad send-events 'disabled'",
             "org.gnome.desktop.peripherals.touchpad tap-and-drag false",
             "org.gnome.desktop.peripherals.touchpad tap-to-click false",
             "org.gnome.desktop.peripherals.touchpad two-finger-scrolling-enabled false",
             "org.gnome.desktop.privacy hide-identity true",
             "org.gnome.desktop.privacy old-files-age 5",
             "org.gnome.desktop.privacy remove-old-temp-files true",
             "org.gnome.desktop.privacy remove-old-trash-files true",
             "org.gnome.desktop.privacy report-technical-problems true",
             "org.gnome.desktop.privacy send-software-usage-stats true",
             "org.gnome.desktop.privacy show-full-name-in-top-bar true",
             "org.gnome.desktop.screensaver picture-options 'spanned'",
             "org.gnome.desktop.screensaver picture-uri 'file:///usr/share/backgrounds/warty-final-ubuntu.png'",
             "org.gnome.desktop.screensaver show-full-name-in-top-bar true",
             "org.gnome.desktop.screensaver show-notifications false",
             "org.gnome.desktop.screensaver status-message-enabled true",
             "org.gnome.desktop.screensaver ubuntu-lock-on-suspend true",
             "org.gnome.desktop.screensaver user-switch-enabled true",
             "org.gnome.desktop.sound event-sounds true",
             "org.gnome.desktop.sound theme-name '__custom'",
             "org.gnome.desktop.wm.preferences action-middle-click-titlebar 'toggle-shade'",
             "org.gnome.desktop.wm.preferences auto-raise true",
             "org.gnome.desktop.wm.preferences focus-mode 'click'",
             "org.gnome.desktop.wm.preferences num-workspaces 1",
             "org.gnome.desktop.wm.preferences resize-with-right-button false",
             "org.gnome.desktop.wm.preferences theme 'Adwaita'",
             "org.gnome.eog.ui disable-trash-confirmation",
             "org.gnome.eog.ui image-gallery true",
             "org.gnome.eog.ui image-gallery-position 'left'",
             "org.gnome.eog.ui image-gallery-resizable true",
             "org.gnome.eog.ui propsdialog-netbook-mode false",
             "org.gnome.eog.ui scroll-buttons false",
             "org.gnome.eog.ui statusbar false",
             "org.gnome.gedit.plugins active-plugins ['docinfo', 'externaltools', 'filebrowser', 'modelines', 'pythonconsole', 'quickopen', 'sort', 'snippets', 'spell', 'time']",
             "org.gnome.gedit.plugins.filebrowser enable-remote true",
             "org.gnome.gedit.plugins.filebrowser.nautilus confirm-trash false",
             "org.gnome.gedit.plugins.pythonconsole font 'Hack 10'",
             "org.gnome.gedit.plugins.time custom-format '%a %e %B %Y, %H%M %Z'",
             "org.gnome.gedit.plugins.time prompt-type 'use-custom-format'",
             "org.gnome.gedit.preferences.editor auto-indent true",
             "org.gnome.gedit.preferences.editor bracket-matching true",
             "org.gnome.gedit.preferences.editor display-line-numbers true",
             "org.gnome.gedit.preferences.editor display-overview-map true",
             "org.gnome.gedit.preferences.editor editor-font 'Hack 10'",
             "org.gnome.gedit.preferences.editor ensure-trailing-newline true",
             "org.gnome.gedit.preferences.editor insert-spaces true",
             "org.gnome.gedit.preferences.editor scheme 'cobalt'",
             "org.gnome.gedit.preferences.editor search-highlighting true",
             "org.gnome.gedit.preferences.editor syntax-highlighting true",
             "org.gnome.gedit.preferences.editor tabs-size 2",
             "org.gnome.gnome-screenshot '$home_dir/Pictures/screenshots'",
             "org.gnome.gnome-screenshot default-file-type 'png'",
             "org.gnome.gnome-screenshot include-border false",
             "org.gnome.gnome-screenshot include-pointer false",
             "org.gnome.login-screen allowed-failures 5",
             "org.gnome.login-screen disable-user-list false",
             "org.gnome.login-screen enable-password-authentication true",
             "org.gnome.login-screen enable-smartcard-authentication false",
             "org.gnome.mutter dynamic-workspaces false",
             "org.gnome.nautilus.compression default-compression-format 'tar.xz'",
             "org.gnome.nautilus.desktop home-icon-visible false",
             "org.gnome.nautilus.desktop network-icon-visible false",
             "org.gnome.nautilus.desktop trash-icon-visible false",
             "org.gnome.nautilus.desktop volumes-visible true",
             "org.gnome.nautilus.list-view default-visible-columns ['name', 'size', 'owner', 'date_modified_with_time']",
             "org.gnome.nautilus.preferences always-use-location-entry true",
             "org.gnome.nautilus.preferences default-folder-viewer 'list-view'",
             "org.gnome.nautilus.preferences mouse-back-button 0",
             "org.gnome.nautilus.preferences mouse-forward-button 0",
             "org.gnome.nautilus.preferences mouse-use-extra-buttons false",
             "org.gnome.nautilus.preferences show-create-link true",
             "org.gnome.nm-applet suppress-wireless-networks-available true",
             "org.gnome.settings-daemon.peripherals.keyboard numlock-state 'on'",
             "org.gnome.settings-daemon.peripherals.keyboard remember-numlock-state true",
             "org.gnome.settings-daemon.peripherals.mouse locate-pointer true",
             "org.gnome.settings-daemon.plugins.color night-light-schedule-automatic true",
             "org.gnome.settings-daemon.plugins.power power-button-action 'suspend'",
             "org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 4800",
             "org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'suspend'",
             "org.gnome.settings-daemon.plugins.power sleep-inactive-battery-timeout 4800",
             "org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'suspend'",
             "org.gnome.settings-daemon.plugins.xsettings hinting 'slight'",
             "org.gnome.shell enabled-extensions ['add-username-toppanel@brendaw.com', 'alternate-tab@gnome-shell-extensions.gcampax.github.com', 'apt-update-indicator@franglais125.gmail.com', 'datetime-format@Daniel-Khodabakhsh.github.com', 'update-extensions@franglais125.gmail.com', 'no-title-bar@franglais125.gmail.com', 'openweather-extension@jenslody.de', 'places-menu@gnome-shell-extensions.gcampax.github.com', 'suspend-button@laserb', 'drive-menu@gnome-shell-extensions.gcampax.github.com', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'apps-menu@gnome-shell-extensions.gcampax.github.com', 'mailnag@pulb.github.com', 'ubuntu-appindicators@ubuntu.com']",
             "org.gnome.shell.window-switcher app-icon-mode 'thumbnail-only'",
             "org.gnome.software external-appstream-system-wide true",
             "org.gnome.software show-ratings true",
             "org.gnome.system.location enabled true",
             "org.gnome.system.location max-accuracy-level 'neighborhood'",
             "org.gnome.Terminal.Legacy.Settings new-terminal-mode 'tab'",
             "org.gnome.Terminal.Legacy.Settings theme-variant 'dark'",
             "org.gnome.Terminal.Legacy.Settings tab-position 'top'"; do
      gsettings set $i
    done
    for i in "/org/gnome/shell/extensions/apt-update-indicator/always-visible false",
             "/org/gnome/shell/extensions/apt-update-indicator/check-cmd-version \"'pkexec apt update'\"",
             "/org/gnome/shell/extensions/apt-update-indicator/interval-unit \"'days'\"",
             "/org/gnome/shell/extensions/apt-update-indicator/notify true",
             "/org/gnome/shell/extensions/apt-update-indicator/output-on-terminal true",
             "/org/gnome/shell/extensions/apt-update-indicator/strip-versions true",
             "/org/gnome/shell/extensions/apt-update-indicator/terminal \"'gnome-terminal -x fish -c'\"",
             "/org/gnome/shell/extensions/apt-update-indicator/update-cmd \"'pkexec apt upgrade -y'\"",
             "/org/gnome/shell/extensions/apt-update-indicator/update-cmd-options \"'custom'\"",
             "/org/gnome/shell/extensions/apt-update-indicator/use-custom-cmd true",
             "/org/gnome/shell/extensions/apt-update-indicator/verbosity 2",
             "/org/gnome/shell/extensions/datetime-format/datemenudate-format \"'%A, %e %B %Y'\"",
             "/org/gnome/shell/extensions/datetime-format/datemenuday-format \"'%A, %e %B'\"",
             "/org/gnome/shell/extensions/datetime-format/statusbar-format \"'%A %e %B %Y, %H%M %Z'\"",
             "/org/gnome/shell/extensions/extensions/position \"'panel'\"",
             "/org/gnome/shell/extensions/extensions/show-add true",
             "/org/gnome/shell/extensions/no-title-bar/buttons-for-snapped true",
             "/org/gnome/shell/extensions/no-title-bar/hide-buttons false",
             "/org/gnome/shell/extensions/no-title-bar/only-main-monitor false",
             "/org/gnome/shell/extensions/openweather/actual-city 0",
             "/org/gnome/shell/extensions/openweather/appid-fc \"'5f45bf8521e04c2e702c6f5a2208adba'\"",
             "/org/gnome/shell/extensions/openweather/center-forecast true",
             "/org/gnome/shell/extensions/openweather/city \"'34.663253, -86.718080>Huntsville, AL>1'\"",
             "/org/gnome/shell/extensions/openweather/days-forecast 3",
             "/org/gnome/shell/extensions/openweather/decimal-places 0",
             "/org/gnome/shell/extensions/openweather/geolocation-provider \"'geocode'\"",
             "/org/gnome/shell/extensions/openweather/position-in-panel \"'right'\"",
             "/org/gnome/shell/extensions/openweather/pressure-unit \"'atm'\"",
             "/org/gnome/shell/extensions/openweather/refresh-interval-current 600",
             "/org/gnome/shell/extensions/openweather/refresh-interval-forcast 600",
             "/org/gnome/shell/extensions/openweather/show-comment-in-forecast true",
             "/org/gnome/shell/extensions/openweather/show-comment-in-panel false",
             "/org/gnome/shell/extensions/openweather/show-text-in-panel true",
             "/org/gnome/shell/extensions/openweather/translate-condition true",
             "/org/gnome/shell/extensions/openweather/unit \"'fahrenheit'\"",
             "/org/gnome/shell/extensions/openweather/use-default-owm-key true",
             "/org/gnome/shell/extensions/openweather/use-symbolic-icons true",
             "/org/gnome/shell/extensions/openweather/weather-provider \"'darksky.net'\"",
             "/org/gnome/shell/extensions/openweather/wind-direction true",
             "/org/gnome/shell/extensions/openweather/wind-speed-unit \"'mph'\"",
             "/org/gnome/shell/extensions/suspend-button/show-two-buttons false",
             "/org/gnome/shell/extensions/update-extensions/interval-unit \"'days'\"",
             "/org/gnome/shell/extensions/update-extensions/system-wide-ext true",
             "/org/gnome/shell/extensions/update-extensions/transient true",
             "/org/gnome/shell/extensions/user-theme/name \"'Obsidian-2'\"",
             "/org/gtk/Settings/FileChooser/clock-format \"'24h'\"",
             "/org/gtk/Settings/FileChooser/date-format \"'with-time'\"",
             "/org/gtk/Settings/FileChooser/location-mode \"'path-bar'\"",
             "/org/gkt/Settings/FileChooser/show-size-column true",
             "/org/gtk/Settings/FileChooser/sort-column \"'name'\"",
             "/org/gtk/Settings/FileChooser/sort-directories-first true",
             "/org/gtk/Settings/FileChooser/sort-order \"'ascending'\"; do
      dconf write $i
    done
    if [ -f $home_dir/Pictures/wallpaper.png ] ; then
      gsettings set org.gnome.desktop.background picture-url 'file://$home_dir/Pictures/wallpaper.png'
    else if [ -f $home_dir/Pictures/wallpaper.jpg ] ; then
      gsettings set org.gnome.desktop.background picture-url 'file://$home_dir/Pictures/wallpaper.jpg'
    else if [ -f $home_dir/Pictures/wallpaper.jpeg ] ; then
      gsettings set org.gnome.desktop.background picture-url 'file://$home_dir/Pictures/wallpaper.jpeg'
    else
      gsettings set com.canonical.unity-greeter background 'file:///usr/share/backgrounds/warty-final-ubuntu.png'
    fi
    case "$user" in
      hunter-adm)
        for i in "org.gnome.gnome-system-monitor show-whose-processes 'all'",
                 "org.gnome.nautilus.preferences confirm-trash false",
                 "org.gnome.nautilus.preferences show-delete-permanently true",
                 "org.gnome.nautilus.preferences show-hidden-files true",
                 "org.gnome.online-accounts whitelisted-providers ['']",
                 "org.gnome.Terminal.Legacy.Settings confirm.close false",
                 "org.gnome.Terminal.Legacy.Settings default-show-menubar false"; do
          gsettings set $i
        done
        dconf write /org/gtk/Settings/FileChooser/show-hidden true ;;
      hunter)
        for i in "org.gnome.gnome-system-monitor show-whose-processes 'all'",
                 "org.gnome.nautilus.preferences confirm-trash false",
                 "org.gnome.nautilus.preferences show-delete-permanently true",
                 "org.gnome.nautilus.preferences show-hidden-files true",
                 "org.gnome.rhythmbox.player play-order 'shuffle'",
                 "org.gnome.rhythmbox.plugins.alternative_toolbar app-menu-display true",
                 "org.gnome.rhythmbox.plugins.alternative_toolbar compact-progressbar true",
                 "org.gnome.rhythmbox.plugins.alternative_toolbar dark-theme true",
                 "org.gnome.rhythmbox.plugins.alternative_toolbar volume-control true",
                 "org.gnome.rhythmbox queue-as-sidebar true",
                 "org.gnome.rhythmbox.sharing enable-browsing true",
                 "org.gnome.rhythmbox.sharing enable-sharing true",
                 "org.gnome.rhythmbox.sharing require-password true",
                 "org.gnome.shell.extensions.mailnag max-visible-emails 15",
                 "org.gnome.shell.extensions.mailnag remove-indicator true",
                 "org.gnome.shell.extensions.mailnag show-avatars true",
                 "org.gnome.shell.extensions.mailnag show-check-for-mail-button false",
                 "org.gnome.shell.extensions.mailnag show-dates true",
                 "org.gnome.shell.extensions.mailnag show-mark-all-as-read-button false",
                 "org.gnome.shell.extensions.mailnag show-settings-button true",
                 "org.gnome.shell favorite-apps ['firefox.desktop']"; do
               "$i
        done
        gsettings reset org.gnome.online-accounts whitelisted-providers
        dconf write /org/gtk/Settings/FileChooser/show-hidden true ;;
      *)
        for i in "org.gnome.gnome-system-monitor show-whose-processes 'user'",
                 "org.gnome.nautilus.preferences confirm-trash true",
                 "org.gnome.nautilus.preferences show-delete-permanently false",
                 "org.gnome.nautilus.preferences show-hidden-files false",
                 "org.gnome.rhythmbox.player play-order 'shuffle'",
                 "org.gnome.rhythmbox.plugins.alternative_toolbar app-menu-display true",
                 "org.gnome.rhythmbox.plugins.alternative_toolbar compact-progressbar true",
                 "org.gnome.rhythmbox.plugins.alternative_toolbar dark-theme true",
                 "org.gnome.rhythmbox.plugins.alternative_toolbar volume-control true",
                 "org.gnome.rhythmbox queue-as-sidebar true",
                 "org.gnome.rhythmbox.sharing enable-browsing true",
                 "org.gnome.rhythmbox.sharing enable-sharing true",
                 "org.gnome.rhythmbox.sharing require-password true": do
          gsettings set $i
        done
        gsettings reset org.gnome.online-accounts whitelisted-providers
        dconf write /org/gtk/Settings/FileChooser/show-hidden false ;;
    esac ;;
esac

set user= 
set home_dir= 


